config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'account', controllers: { registrations: "registrations" }
  get 'home/index'

  root 'home#index'

  get 'dashboard', to: 'dashboard#index'

  scope '/dashboard' do

    resources :users

    resources :events do
      resources :locations
      resources :stories, except: :show
      resource :gift
    end

  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  # Authenticate: Required to use devise helpers
  before_action :authenticate_user!



  def index
    # unless current_user.has_role? :admin
    #   flash[:error] = ""
    # end
    authorize! :index, :dashboard

    unless current_user.event_id.nil?
      @event = Event.find_by_id(current_user.event_id)
      # @guests = @event.users.with_role(:guest, @event)
      @guests = @event.users.with_role(:guest, @event).includes(:partner).as_json(include: { partner: { only: [:name] } })

    else
      @event = Event.new
    end

    @guest_user = User.new

  end


end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/dashboard/_content_header.html.erb
<section class="content-header">
  <h1>
    <%= yield :page_header %>
    <small><%= yield :page_description %></small>
  </h1>
</section>

app/views/layouts/dashboard/_footer.html.erb
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
</footer>

app/views/layouts/dashboard/_header.html.erb
  <header class="main-header">

    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-thumbs-o-up"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the messages -->
                <ul class="menu">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <!-- User Image -->
                        <%= image_tag("user2-160x160.jpg", class: "img-circle", alt: "User Image") %>
                      </div>
                      <!-- Message title and timestamp -->
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <!-- The message -->
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <!-- end message -->
                </ul>
                <!-- /.menu -->
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- /.messages-menu -->

          <!-- Notifications Menu -->
          <li class="dropdown notifications-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-question-circle"></i>
              <span class="label label-warning">10</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <!-- Inner Menu: contains the notifications -->
                <ul class="menu">
                  <li><!-- start notification -->
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                  </li>
                  <!-- end notification -->
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>
          <!-- Tasks Menu -->
          <li class="dropdown tasks-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-thumbs-o-down"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- Inner menu: contains the tasks -->
                <ul class="menu">
                  <li><!-- Task item -->
                    <a href="#">
                      <!-- Task title and progress text -->
                      <h3>
                        Design some buttons
                        <small class="pull-right">20%</small>
                      </h3>
                      <!-- The progress bar -->
                      <div class="progress xs">
                        <!-- Change the css width attribute to simulate progress -->
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer">
                <a href="#">View all tasks</a>
              </li>
            </ul>
          </li>
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <%= icon('user') %>
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs"><%= current_user.email %></span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <%= image_tag("user2-160x160.jpg", class: "img-circle", alt: "User Image") %>

                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

app/views/layouts/dashboard/_sidebar.html.erb
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header"><%= t('dashboard.sidebar.title').upcase %></li>

        <!-- Optionally, you can add icons to the links -->
        <li class="<%= 'active' if current_page?(dashboard_path) %>">
          <%= link_to(dashboard_path) do %>
            <%= icon('home') %>
            <span><%= t('dashboard.sidebar.start') %></span>
          <% end %>
        </li>

        <% unless current_user.event.nil? %>

          <li class="treeview <%= 'active' if controller_name == 'users' %>">
            <a href="#"><%= icon('heart') %> <span>Novios</span> <i class="fa fa-angle-left pull-right"></i></a>
            <ul class="treeview-menu">
              <li class="<%= 'active' if current_page?(@groom) %>">
                  <%= link_to @groom do %>
                    <%= icon('mars') %> <%= t('dashboard.sidebar.groom') %>
                  <% end %>
              </li>

              <li  class="<%= 'active' if current_page?(@bride) %>">
                  <%= link_to @bride do %>
                    <%= icon('venus') %> <%= t('dashboard.sidebar.bride') %>
                  <% end %>
              </li>
            </ul>
          </li>


          <li class="<%= 'active' if controller_name == 'locations' %>">
            <% if @event.location.nil? %>
              <% event_path = new_event_location_path(@event) %>
            <% else %>
              <% event_path = event_location_path(@event, @event.location) %>
            <% end %>

            <%= link_to(event_path) do %>
              <%= icon('map-marker') %>
              <span><%= t('dashboard.sidebar.location') %></span>
            <% end %>
          </li>

          <li class="<%= 'active' if controller_name == 'stories' %>">
            <%= link_to(event_stories_path(@event)) do %>
              <%= icon('venus-mars') %>
              <span><%= t('dashboard.sidebar.history') %></span>
            <% end %>
          </li>


          <li class="<%= 'active' if controller_name == 'gifts' %>">
            <% if @event.gift.nil? %>
              <% gift_path = new_event_gift_path(@event) %>
            <% else %>
              <% gift_path = event_gift_path(@event) %>
            <% end %>

            <%= link_to(gift_path) do %>
              <%= icon('gift') %>
              <span><%= t('dashboard.sidebar.gift') %></span>
            <% end %>
          </li>

        <% end %>

        <li>
          <%= link_to(destroy_user_session_path, method: :delete) do %>
            <%= icon('sign-out') %>
            <span><%= t('dashboard.sidebar.signout') %></span>
          <% end %>
        </li>

      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>