config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'account', controllers: { registrations: "registrations" }
  get 'home/index'

  root 'home#index'

  get 'dashboard', to: 'dashboard#index'

  scope '/dashboard' do

    resources :users

    resources :events do
      resources :locations
      resources :stories, except: :show
      resource :gift
    end

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  enum confirmation_status: [:unknown, :nok, :ok]

  rolify
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :profile_image, type: :image

  belongs_to :event


  has_one :partner, class_name: 'User', foreign_key: :partner_id,
          dependent: :nullify

  after_create :set_partnership


  validates :roles, :presence => true

  def full_name
    "#{first_name} #{last_name}"
  end

  def create_account
      account = Account.new(:email => email, :subdomain => subdomain )
      account.save!
  end
  
  def as_json(options={})
    super(:include => {
            :partner => {:only => [:name]}
          }
    )
  end

  private

  def set_partnership
    unless self.partner_id.nil?
       u = User.find(self.partner_id)
       u.partner_id = self.id
       u.save
    end
  end

  def email_required?
    if self.is_admin? then
      true
    else
      false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  layout 'dashboard'

  def show
    @user = User.find(params[:id])
    unless @user.is_bride_of?(@user.event) || @user.is_groom_of?(@user.event)
      redirect_to dashboard_path
    end
  end

  def new
    @role = params[:role]
    if ['groom', 'bride'].include?(@role)
      @user = User.new
    else
      redirect_to dashboard_path
    end
  end

  def edit

  end

  def create

    @user = User.new(user_params)

    @user.password = '12'
    @user.add_role params[:user][:role], current_user.event
    @user.event = current_user.event
    @user.skip_confirmation!

    if(params[:user][:has_partner] == "true")
      p = @user.build_partner(name: params[:user][:partner_name],
                              email: params[:user][:partner_email],
                              menu: params[:user][:partner_menu])
      p.password = '12'
      p.add_role params[:user][:role], current_user.event
      p.add_role "partner", current_user.event
      p.event = current_user.event
      p.skip_confirmation!

    end
    respond_to do |format|
      if @user.save
        # render json: @user
        # format.json { render :index, status: :created, location: @story }
        format.json {
          render :json => {
            user: @user,
            partner: @user.partner
          }
        }
      else
        render json: @user.errors, status: :unprocessable_entity
      end
    end

  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    head :no_content
  end

  def update
    if(@user.is_guest_of?(@user.event))
      @user.skip_reconfirmation!
    end

    respond_to  do |format|
      if @user.update(user_params)
        format.html { redirect_to @user,
          flash: { success: t('forms.users.edit_ok') } }
        format.json { render json: @user, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    if params[:user][:role] == 'guest'
      params.require(:user).permit(:name, :email, :menu, :confirmation_status)
    elsif (['groom', 'bride'].include?(params[:user][:role]) ||  params[:user][:role] == 'couple')
      params.require(:user).permit(:first_name, :profile_image, :last_name, :event_id, :subdomain,
      :biography, :facebook, :twitter, :instagram, :linkedin, :pinterest)
    end
  end

  def couple_params
    params.require(:user).permit(:first_name, :profile_image, :last_name, :event_id, :subdomain,
      :biography, :facebook, :twitter, :instagram, :linkedin, :pinterest)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_social_item.html.erb
<li class="list-group-item">

  <%= icon(network) %>
  <b><%= t(network) %></b>
  <div class="pull-right <%= network %>">
  <% if current_page?(action: 'show') %>
    <%= @user[network].present? ? link_to(@user[network], @user[network],
      :target => "_blank") : t('users.show.no_info') %>
  <% elsif current_page?(action: 'edit') %>
    <%= f.input network, input_html:
        { class: 'social-network', value: @user[network] },
          placeholder: t('users.edit.socialnetwork_ph', sn: network),
        label: false  %>
  <% end %>
  </div>

</li>

app/views/users/edit.html.erb
<% content_for :page_header do %>
  <%= t("users.show.#{@user.roles.first.name}") %>
<% end %>

<% content_for :page_description do %>
  <%= @user.first_name %> <%= @user.last_name %>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-body box-profile">
        <%= simple_form_for @user do |f| %>

          <%= f.button :submit, t('.save_btn'), class: "btn btn-primary btn-block" %>

          <div class="header-profile">
            <div class="row">
              <div class="col-md-4">
                <div class = "picture-profile">
                  <p><%= t('.profile_picture') %></p>
                  <div id = "imgpreview">
                    <%= @user.profile_image.present? ?
                    image_tag(attachment_url(@user, :profile_image, :fill, 300, 300, format: "jpg"), class: "profile-img img-circle")
                    : icon('user') %>
                  </div>
                   <p class="text-muted"><small><%= t('.picture_description', role: t(@user.roles.first.name)) %></small></p>
                  <%= f.input :profile_image, as: :attachment, direct: true, presigned: true, label: false,
                    input_html: { data: { progressbar: 'progress-bar',
                    progressbarcontainer: 'progress-bar-container' } },
                    wrapper_html: { class: 'form-group-sm' }  %>
      <div id="progress-bar-container">
        <div class="progress">
          <div id="progress-bar" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
            <span class="sr-only">0% Complete</span>
          </div>
        </div>
      </div>
                </div>
              </div>
              <div class="col-md-8">
                <div style="display:block name-profile">
                  <%= f.input :role, as: :hidden, input_html: { value: 'couple' } %>
                  <%= f.input :first_name, input_html: { value: @user.first_name } %>
                  <%= f.input :last_name , input_html: { value: @user.last_name  } %>
                  <%= f.input :biography , input_html: { value: @user.biography  } %>
                </div>
              </div>
            </div>
          </div>

          <ul class="social-icons icon-circle list-group list-group-unbordered">
            <%= render 'social_item', network: 'twitter', f: f %>

            <%= render 'social_item', network: 'facebook', f: f %>

            <%= render 'social_item', network: 'linkedin', f: f %>

            <%= render 'social_item', network: 'instagram', f: f %>

            <%= render 'social_item', network: 'pinterest', f: f %>

            <%= render 'social_item', network: 'internet-explorer', f: f %>
          </ul>

          <%= f.button :submit, t('.save_btn'), class: "btn btn-primary btn-block" %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :page_header do %>
    <%= t(".#{@role}") %>
<% end %>

<% content_for :page_description do %>
<%= t('.description') %>
<% end %>

<%= simple_form_for(@user) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :biography %>
  <%= f.input :role, as: :hidden, input_html: { value: @role } %>
  <%= f.input :profile_image, as: :attachment, direct: true, presigned: true %>
  <%= f.button :submit, t('.create_button') %>
<% end %>

app/views/users/show.html.erb
<% content_for :page_header do %>
  <%= t("users.show.#{@user.roles.first.name}") %>
<% end %>

<% content_for :page_description do %>
  <%= @user.first_name %> <%= @user.last_name %>
<% end %>

 <div class="row">
   <div class="col-md-12">
     <div class="box box-primary">
            <div class="box-body box-profile">
              <%= link_to edit_user_path(@user), class: "btn btn-primary btn-block" do %>
                <b><%= t('users.show.edit_btn') %></b>
              <% end %>

              <div class="header-profile">
                <div class="row">
                  <div class="col-md-4">
                    <div class = "picture-profile">
                      <p><%= t('.profile_picture') %></p>
                      <%= @user.profile_image.present? ?
                      image_tag(attachment_url(@user, :profile_image, :fill, 300, 300, format: "jpg"), class: "profile-img img-circle")
                      : icon('user') %>
                      <p class="text-muted"><small><%= t('.picture_description', role: t(@user.roles.first.name)) %></small></p>
                    </div>
                  </div>
                  <div class="col-md-8">
                  <div>
                    <h3 class="profile-username">
                      <%= @user.full_name.present? ? @user.full_name : t("users.show.name") %>
                    </h3>

                    <p class="biography text-muted">
                      <%= @user.biography.present? ? @user.biography : t('.biography_description') %>
                    </p></div>
                  </div>
                </div>
              </div>

              <ul class="social-icons icon-circle list-group list-group-unbordered">
                <%= render 'social_item', network: 'twitter' %>

                <%= render 'social_item', network: 'facebook' %>

                <%= render 'social_item', network: 'linkedin' %>

                <%= render 'social_item', network: 'instagram' %>

                <%= render 'social_item', network: 'pinterest' %>

                <%= render 'social_item', network: 'internet-explorer' %>
              </ul>

              <%= link_to edit_user_path(@user), class: "btn btn-primary btn-block" do %>
                <b><%= t('users.show.edit_btn') %></b>
              <% end %>

            </div>
          </div>
   </div>
 </div>