config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'account', controllers: { registrations: "registrations" }
  get 'home/index'

  root 'home#index'

  get 'dashboard', to: 'dashboard#index'

  scope '/dashboard' do

    resources :users

    resources :events do
      resources :locations
      resources :stories, except: :show
      resource :gift
    end

  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  # rolify helper
  resourcify

  has_many :users
  has_many :stories
  has_one :location
  has_one :gift

  before_destroy :unassign_admin
  before_destroy :destroy_guests

  before_create :create_bride
  before_create :create_groom


  def days_left
    (date.to_date - Time.now.to_date).to_i
  end

  def days_left_since_created
    (date.to_date - created_at.to_date).to_i
  end

  def ongoing_days
    days_left_since_created - days_left
  end

  def total_guests
    users.with_role(:guest, self).count
  end

  def confirmed_guests
    users.with_role(:guest, self).ok.count
  end

  def unconfirmed_guests
    users.with_role(:guest, self).nok.count
  end

  def unknown_guests
    users.with_role(:guest, self).unknown.count
  end

  def ongoing_days_percent
    ((ongoing_days*100)/days_left_since_created).to_i
  end

  def as_json(options={})
    h = super(options)
    h[:daysLeft] = days_left
    h[:ongoing_days_percent] = ongoing_days_percent
    h[:total_guests] = total_guests
    h[:confirmed_guests] = confirmed_guests
    h[:unconfirmed_guests] = unconfirmed_guests
    h[:unknown_guests] = unknown_guests
    h
  end


  private

  def unassign_admin
    users.with_role(:admin).update_all(event_id: nil)
  end

  def destroy_guests
    users.destroy_all
  end

  def create_bride
    users.build(password: '12', roles: [ Role.new(name: 'bride', resource: self ) ] )
  end

  def create_groom
    users.build(password: '12', roles: [ Role.new(name: 'groom', resource: self ) ] )
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  layout 'dashboard'

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # Authenticate: Required to use devise helpers
  before_action :authenticate_user!, except: [:show, :index]

  #CanCanCan
  load_and_authorize_resource

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    case params[:form]
    when "location"
      render 'location'
    else
      render action: :edit
    end

  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)


    respond_to do |format|
      if @event.save

        # Get current admin user, assign event he just created
        current_user.event = @event
        current_user.save!

        format.html { redirect_to dashboard_path, flash: { success: t('forms.events.success') } }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end


    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :time, :description, :address, :address_description, :latitude, :longitude)
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Description</th>
      <th>Address</th>
      <th>Address description</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.date %></td>
        <td><%= event.time %></td>
        <td><%= event.description %></td>
        <td><%= event.latitude %></td>
        <td><%= event.longitude %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/location.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 0,
      "lng": 0,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>


<% content_for :page_header do %>
    <%= t("location.name") %>
<% end %>

<% content_for :page_description do %>
    <%= t("location.description")  %>
<% end %>

<%= simple_form_for @event do |f| %>
  <%= f.input :address %>
  <%= f.input :address_description %>
  <%= f.submit %>
<% end %>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'>a</div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @event.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @event.longitude %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>