config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'account', controllers: { registrations: "registrations" }
  get 'home/index'

  root 'home#index'

  get 'dashboard', to: 'dashboard#index'

  scope '/dashboard' do

    resources :users

    resources :events do
      resources :locations
      resources :stories, except: :show
      resource :gift
    end

  end

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :event
  
  attachment :photo
  
  validates_presence_of :name
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    layout 'dashboard'

    # This method also load the instance variables on actions like CREATE.
    # Having the instance variable defined twice, by the method and manually
    # caused uploads not to work
    load_and_authorize_resource

    def index
        @event = Event.find(params[:event_id])
        @stories = Story.order(date: :asc)
        @story = Story.new
    end

    def destroy
        Story.find(params[:id]).destroy
        respond_to do |format|
            format.html { redirect_to event_stories_url(params[:event_id]),
                success: 'Event was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    # POST /events
    # POST /events.json
    def create
        respond_to do |format|
          if @story.save
            format.html { redirect_to event_stories_path(params[:event_id]),
                flash: { success: t('forms.stories.success') } }
            format.json { render :index, status: :created, location: @story }
          else
            @stories = Story.order(date: :asc)
            format.html { render :index }
            format.json { render json: @event.errors,
                status: :unprocessable_entity }
          end
        end
    end

    private
    def story_params
      params.require(:story).permit(:name, :description, :date, :photo,
                                    :photo_id)
    end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_story.html.erb
<!-- timeline time label -->
<li class="time-label">
    <span class="bg-red">
        <%= l story.date, format: :long_s %>
    </span>
</li>
<!-- /.timeline-label -->

<!-- timeline item -->
<li>
    <!-- timeline icon -->
    <i class="fa fa-heart bg-red"></i>
    <div class="timeline-item">
        <h3 class="timeline-header"><a href="#"><%= story.name %></a> ...</h3>

        <div class="timeline-body">
            <%= image_tag attachment_url(story, :photo, :fill, 200, 200,
            format: "jpg"), class: "img-rounded" if story.photo.present? %>
                <%= story.description %>
        </div>
        <div class="timeline-footer">
            <%= button_to event_story_path(@event, story), method: :delete, data: { confirm: t('r_u_sure') },
                class: "btn btn-default btn-xs" do %>
                <%= icon('trash') %>
                <%= t('stories.index.delete_story') %>
            <% end %>
        </div>
    </div>
</li>

app/views/stories/_story_form.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title"><%= t('stories.index.new_story') %></h3>
  </div>
  <!-- /.box-header -->
  <!-- form start -->
  <%= simple_form_for [@event, @story], class: "form-horizontal" do |f| %>
    <div class="box-body">
    <div class="col-md-8">
      <div class="col-md-6">
        <%= f.input :name, placeholder: t('stories.index.name_ph'), wrapper_html: { class: 'form-group-sm' } %>
      </div>

      <div class="col-md-6">
        <%= f.input :date, wrapper_html: { class: 'form-group-sm' } %>
      </div>


      <div class="col-md-12">
        <%= f.input :description, wrapper_html: { class: 'form-group-sm' } %>
      </div>
    </div>
    <div class="col-md-4">
      <%= f.input :photo, as: :attachment, direct: true, presigned: true,
          input_html: { data: { progressbar: 'progress-bar',
          progressbarcontainer: 'progress-bar-container' } },
          wrapper_html: { class: 'form-group-sm' }  %>
      <div id="imgpreview"></div>
      <div id="progress-bar-container">
        <div class="progress">
          <div id="progress-bar" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
            <span class="sr-only">0% Complete</span>
          </div>
        </div>
      </div>

    </div>

    </div>

    <div class="box-footer">
      <%= f.button :submit, t('stories.index.create_btn'), class: "btn btn-block pull-right btn-primary" %>
    </div>


  <% end %>
</div>

app/views/stories/index.html.erb
<% content_for :page_header do %>
    <%= t(".name") %>
<% end %>

<% content_for :page_description do %>
    <%= t(".description")  %>
<% end %>

<%= render 'story_form' %>

<ul class="timeline">
    <%= render @stories %>
</ul>